"""
scheduler.py - Background task scheduler for YouTube Shorts automation

This module manages recurring tasks using APScheduler (Advanced Python Scheduler).
It runs the main video generation and upload pipeline on a configurable schedule.

Handles:
- Scheduling video generation every N hours
- Graceful error handling and logging
- YouTube token refresh
- Configurable via environment variables

Usage:
    from scheduler import start_scheduler, stop_scheduler
    
    # Start scheduler in background
    scheduler = start_scheduler(interval_hours=6)
    
    # Scheduler runs automatically; stop when done
    stop_scheduler(scheduler)
"""

import os
import logging
import shutil
import threading
from datetime import datetime
from typing import Optional
from pathlib import Path
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
from apscheduler.triggers.cron import CronTrigger
import pytz
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# Global flag to prevent concurrent task runs
_task_running = False
_task_lock = threading.Lock()

# Load environment variables
load_dotenv()


def cleanup_output_folder(output_dir: str = 'output/shorts'):
    """
    Delete the output folder and all its contents after successful upload.
    
    Args:
        output_dir (str): Path to the output folder to delete (default: 'output/shorts')
    
    Returns:
        bool: True if cleanup was successful, False otherwise
    """
    try:
        output_path = Path(output_dir)
        if output_path.exists():
            logger.info(f"🗑️  Cleaning up output folder: {output_path}")
            shutil.rmtree(output_path)
            logger.info(f"✅ Output folder deleted successfully")
            return True
        else:
            logger.warning(f"⚠️  Output folder not found: {output_path}")
            return True
    except Exception as e:
        logger.error(f"❌ Failed to cleanup output folder: {e}")
        return False


def generate_shorts_video():
    """
    Main task: Generate and upload a YouTube Shorts video.
    
    This function:
    1. Generates a viral idea using Gemini
    2. Creates an optimized script
    3. Generates TTS audio
    4. Creates visuals and captions
    5. Composes the video
    6. Uploads to YouTube
    7. Logs results
    
    Handles all exceptions gracefully and logs failures.
    Prevents concurrent runs using a lock.
    """
    global _task_running
    
    # Prevent overlapping task runs
    with _task_lock:
        if _task_running:
            logger.warning("⚠️  Task already running. Skipping this cycle.")
            return {'status': 'skipped', 'message': 'Task already running'}
        _task_running = True
    
    logger.info("=" * 80)
    logger.info("🎬 STARTING SHORTS GENERATION TASK")
    logger.info("=" * 80)
    
    try:
        # Import modules here to allow for better error handling
        from scripts.config import get_config
        from scripts.idea_generator import IdeaGenerator
        from scripts.short_script_creator import ShortScriptCreator
        # Use new gTTS helper
        from src.tts_generator import generate_voice
        from scripts.caption_generator import CaptionGenerator
        from scripts.video_editor import VideoEditor
        from scripts.thumbnail_generator import ThumbnailGenerator
        from scripts.utils import setup_logging, log_metadata
        
        # Setup
        config = get_config()
        setup_logging()
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        topic = os.getenv('TARGET_TOPIC', 'python programming')
        duration = config.video_duration_seconds
        
        logger.info(f"📋 Topic: {topic}")
        logger.info(f"⏱️  Duration: {duration} seconds")
        logger.info(f"🕐 Timestamp: {timestamp}")
        
        # Step 1: Generate idea
        logger.info("\n[1/7] Generating viral idea with Gemini...")
        idea_gen = IdeaGenerator()
        ideas = idea_gen.generate_ideas(
            topic=topic,
            num_ideas=1,
            duration_seconds=duration
        )
        
        if not ideas or len(ideas) == 0:
            raise ValueError("❌ No ideas generated by Gemini")
        
        idea = ideas[0]
        logger.info(f"✅ Idea: {idea.get('title', 'Untitled')}")
        logger.info(f"   Description: {idea.get('hook', '')[:100]}...")
        
        # Step 2: Create script
        logger.info("\n[2/7] Creating optimized script...")
        script_creator = ShortScriptCreator()
        script_result = script_creator.create_script(idea, duration_seconds=duration)
        # `create_script` returns a dict with 'script' key; support legacy string too
        if isinstance(script_result, dict):
            script = script_result.get('script', '')
        else:
            script = str(script_result)
        logger.info(f"✅ Script created ({len(script.split())} words)")
        
        # Step 3: (DEFERRED) Per-segment TTS generation will be handled by the VideoEditor.
        # We avoid creating a single full audio file here to prevent hard failures
        # when the environment lacks FFmpeg/pydub; VideoEditor will use gTTS
        # fallback to create per-segment MP3s.
        logger.info("\n[3/7] Skipping full-file TTS; will generate per-segment audio in editor.")
        audio_path = None
        
        # Step 4: Generate captions
        logger.info("\n[4/7] Generating captions...")
        caption_gen = CaptionGenerator(duration_seconds=duration)
        # Create simple visual cues splitting the duration evenly by sentence
        sentences = [s.strip() for s in script.split('.') if s.strip()]
        if not sentences:
            sentences = [script]

        visual_cues = []
        seg_len = max(1, duration / len(sentences))
        for i in range(len(sentences)):
            visual_cues.append({'time_seconds': i * seg_len, 'cue': sentences[i] if i < len(sentences) else ''})

        captions = caption_gen.generate_from_visual_cues(visual_cues, script)
        srt_output = Path(f"output/shorts/captions_{timestamp}.srt")
        saved = caption_gen.save_srt(captions, srt_output)
        srt_path = str(srt_output) if saved else None
        logger.info(f"✅ Captions: {srt_path}")
        
        # Step 5: Create visuals
        logger.info("\n[5/7] Creating visuals and video composition...")
        thumbnail_gen = ThumbnailGenerator()
        # ThumbnailGenerator expects an output directory (Path), not a filename.
        thumbnail_path = thumbnail_gen.generate_thumbnail(
            title=idea.get('title', 'Amazing Tech Tip'),
            output_dir=Path("output/shorts")
        )
        logger.info(f"✅ Thumbnail: {thumbnail_path}")
        
        # Step 6: Assemble video
        logger.info("\n[6/7] Assembling final video...")
        video_editor = VideoEditor()
        # Pass structured script data (script + visual_cues) so the editor can
        # generate per-segment slides and per-segment TTS for a dynamic video.
        script_data = script_result if isinstance(script_result, dict) else {
            'script': script,
            'duration_seconds': duration,
            'visual_cues': visual_cues
        }

        video_path = video_editor.create_shorts_video(
            script_data=script_data,
            captions_srt_path=srt_path,
            thumbnail_path=thumbnail_path,
            title=idea.get('title'),
            output_file=f"output/shorts/video_{timestamp}.mp4",
            timestamp=timestamp
        )
        logger.info(f"✅ Video created: {video_path}")
        
        # Step 7: Upload to YouTube
        logger.info("\n[7/7] Uploading to YouTube...")
        # Upload helper lives in src.uploader
        from src.uploader import upload_to_youtube
        
        video_metadata = {
            'title': idea.get('title', 'Amazing Tech Tip'),
            'description': f"{idea.get('description', '')}\n\n#Shorts #Coding #Tutorial",
            'tags': ['Shorts', 'Coding', 'Python', 'Tutorial', topic],
            'categoryId': '22'  # Education category
        }
        
        try:
            video_id = upload_to_youtube(
                video_path=video_path,
                title=video_metadata.get('title', ''),
                description=video_metadata.get('description', ''),
                tags=','.join(video_metadata.get('tags', [])),
                thumbnail_path=thumbnail_path
            )
            if not video_id:
                raise Exception("Upload returned no video ID")
            logger.info(f"✅ Video uploaded! ID: {video_id}")
            logger.info(f"🎉 View at: https://youtube.com/shorts/{video_id}")
        except Exception as upload_error:
            logger.error(f"❌ Upload failed: {upload_error}")
            logger.error(f"🔧 Check YouTube credentials and token validity")
            raise
        
        # Step 8: Cleanup output folder after successful upload
        logger.info("\n[8/8] Cleaning up temporary files...")
        if os.getenv('CLEANUP_OUTPUT_AFTER_UPLOAD', 'true').lower() in ('true', '1', 'yes'):
            cleanup_output_folder('output/shorts')
        else:
            logger.info("↩️  Cleanup disabled (CLEANUP_OUTPUT_AFTER_UPLOAD=false)")
        
        # Log success
        logger.info("\n" + "=" * 80)
        logger.info("✅ SHORTS GENERATION COMPLETE")
        logger.info("=" * 80)
        
        return {
            'status': 'success',
            'video_id': video_id,
            'timestamp': timestamp,
            'topic': topic
        }
        
    except Exception as e:
        logger.error("\n" + "=" * 80)
        logger.error("❌ SHORTS GENERATION FAILED")
        logger.error("=" * 80)
        logger.error(f"Error: {str(e)}")
        logger.error("Traceback:", exc_info=True)
        
        # Here you could add Slack notifications or other alerting
        return {
            'status': 'failed',
            'error': str(e),
            'timestamp': datetime.now().strftime("%Y%m%d_%H%M%S")
        }
    finally:
        # Always release the lock
        with _task_lock:
            _task_running = False


def generate_and_upload_short():
    """
    Public wrapper with the name `generate_and_upload_short` so external
    modules (or `scripts/runner.py`) can import and call the job directly.
    Returns the same dict result as `generate_shorts_video()`.
    """
    return generate_shorts_video()


def start_scheduler(interval_hours: int = None, schedule_hour: int = None, timezone_str: str = None, debug: bool = False) -> BackgroundScheduler:
    """
    Start the background scheduler.

    Args:
        interval_hours (int, optional): Hours between runs (fallback).
        schedule_hour (int, optional): If provided, schedule daily at this hour (0-23).
        timezone_str (str, optional): Timezone name (pytz) for the cron schedule.
        debug (bool, optional): Enable APScheduler debug logging.

    Returns:
        BackgroundScheduler: The running scheduler instance.
    """
    # Read env overrides
    if schedule_hour is None:
        env_hour = os.getenv('UPLOAD_SCHEDULE_HOUR') or os.getenv('UPLOAD_SCHEDULE_HOURS')
        try:
            schedule_hour = int(env_hour) if env_hour is not None else None
        except Exception:
            schedule_hour = None

    if interval_hours is None:
        try:
            interval_hours = int(os.getenv('UPLOAD_SCHEDULE_HOURS', 12))
        except Exception:
            interval_hours = 12

    if timezone_str is None:
        timezone_str = os.getenv('LOCAL_TIMEZONE', os.getenv('TZ', 'Asia/Kolkata'))

    logger.info(f"⏰ Scheduler configuration: interval_hours={interval_hours}, schedule_hour={schedule_hour}, timezone={timezone_str}")

    scheduler = BackgroundScheduler(daemon=True)

    # Choose trigger: daily at specific hour (CronTrigger) if schedule_hour provided,
    # otherwise fall back to interval trigger (every N hours).
    if schedule_hour is not None:
        try:
            tz = pytz.timezone(timezone_str)
        except Exception:
            logger.warning(f"⚠️  Invalid timezone '{timezone_str}', falling back to UTC")
            tz = pytz.UTC

        trigger = CronTrigger(hour=schedule_hour, minute=0, timezone=tz)
        job = scheduler.add_job(
            func=generate_shorts_video,
            trigger=trigger,
            id='shorts_generator',
            name='Generate and upload YouTube Shorts (daily cron)',
            replace_existing=True,
            misfire_grace_time=300
        )
        logger.info(f"✅ Scheduled daily job at hour={schedule_hour} ({timezone_str})")
    else:
        # Interval fallback
        job = scheduler.add_job(
            func=generate_shorts_video,
            trigger=IntervalTrigger(hours=interval_hours),
            id='shorts_generator',
            name='Generate and upload YouTube Shorts (interval)',
            replace_existing=True,
            misfire_grace_time=300
        )
        logger.info(f"✅ Scheduled interval job every {interval_hours} hours")

    # Start scheduler
    try:
        scheduler.start()

        if schedule_hour is not None:
            logger.info(f"✅ Scheduler started - next daily run at hour {schedule_hour} ({timezone_str})")
        else:
            logger.info(f"✅ Scheduler started - next run in {interval_hours} hours")

        if debug:
            logger.info("🐛 Debug mode enabled - job details:")
            for job in scheduler.get_jobs():
                logger.info(f"   - {job.name}: {job.trigger}")

        return scheduler

    except Exception as e:
        logger.error(f"❌ Failed to start scheduler: {e}")
        raise


def stop_scheduler(scheduler: BackgroundScheduler):
    """
    Stop the background scheduler.
    
    Args:
        scheduler (BackgroundScheduler): The scheduler instance to stop.
    
    Example:
        stop_scheduler(scheduler)
    """
    if scheduler and scheduler.running:
        logger.info("🛑 Stopping scheduler...")
        scheduler.shutdown()
        logger.info("✅ Scheduler stopped")
    else:
        logger.warning("⚠️  Scheduler is not running")


def run_once_and_exit():
    """
    Run the video generation task once and exit (for manual testing).
    
    Useful for:
    - Testing the pipeline locally
    - Manual triggering via CLI
    - Running on a serverless platform
    
    Example:
        python scheduler.py
    """
    logger.info("🎬 Running video generation once...")
    result = generate_shorts_video()
    logger.info(f"Result: {result}")
    return result


if __name__ == '__main__':
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Run once (for manual testing)
    run_once_and_exit()
